### PR TITLE
[498847] Add extension for debug providers

### PR DESCRIPTION
**Pull request by eharris369**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=498847

**Comment by elsony** [comment]
1. Given that this extension is going to be public, the implementation class org.eclipse.cft.server.core.internal.debug.CloudFoundryDebugProvider should be part of the public package instead of the internal package.
2. There are 2 existing debug provider are always on the list NgrokDebugProvider and SshDebugProvider.  The implementation of SshDebugProvider.isDebugSupported() is just checking if it is a java project and supports ssh. How does the framework decide which debug provider to use?  Should the extension point has filters. e.g. on the server type and module type? The NgrokDebugProvider and SshDebugProvider implementation can then moved to an extension defined on the default branding plugins instead?
3. The schema file needs to fill in the fields, e.g. description, since, api information, and move the copyright to the copyright section.

**Comment by nierajsingh** [comment]
One thing to change for public API is to use public types. AbstractDebugProvider should use IServer and IModule instead of CloudFoundryServer and CloudFoundryApplicationModule, respectively, to be consistent with other public API that we have. See AbstractApplicationDelegate.

**Comment by elsony** [comment]
4. The list of supported module are specific to the debugProvider. Should the module type list be elements within the debugProvider element instead of on the same level in the schema? 
5. Add copyright statement to org.eclipse.cft.server.core.AbstractDebugProvider 
6. Add class comment to org.eclipse.cft.server.core.AbstractDebugProvider since it is a public API
7. Some updated files does not have the year changed in copyright statements
8. Update plugin version number for org.eclipse.cft.server.core to 1.1.0

**Pull request merged**
