### PR TITLE
[514869] - allow application URL specification with "routes" in

### PR DESCRIPTION
**Pull request by D054981**
Hi there,
this is my first contribution to this project.
Please find my proposal for the issue 514869 from bugzilla.
This should allow now to specify the "routes" in the manifest.yml and get the application URL's setup properly in CF.

BR André

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=514869

**Comment by nierajsingh** [comment]
Hi,

Thanks for submitting this PR for "routes" support in CFT. We appreciate the work that you put into this. 

We plan to review and add your changes to the future CFT 1.1.1 release (Oxygen.1) soon after Eclipse Oxygen is released on June 28.

At the moment we've shut down feature development for the current CFT 1.1.0 release, in preparation for the Oxygen release in a few weeks, but once we re-open master branch for new features we'll review your PR and update on any possible changes in the associated bugzilla here:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=514869

Thanks again, and we'll update once we are ready to accept new features for CFT in just a few weeks from now.

**Comment by nierajsingh** [comment]
Sorry for the delay in reviewing your Pull Request. We are now just beginning work on Oxygen.1 and have looked at your contribution.

Before we can accept this, there are some requirements on the legal Eclipse side that need to be met before we can merge your contribution into CFT. 

1. If you haven’t yet signed the Eclipse ECA,  please log into Eclipse using your Eclipse account and sign the ECA:
https://www.eclipse.org/legal/ECA.php

2. The git commits should also include a “Signed-off-by“ entry:

https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=5936adf038460

This is required for the Eclipse IP log tools to detect your contribution for IP review.

3. Alternately, instead of dealing with git commits with correct footers in your pull request, you can just submit a patch with all the code changes listed below and attach it to the bugzilla:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=514869

When attaching the patch to the bugzilla, please also do the following in the “Create New Attachment” page: 
Under “Flags”, please select ‘+’ as a value for “iplog” field.

Note that attaching a patch to a bugzilla still requires signing the Eclipse ECA before we can apply your patch to the code base.

In addition, there are these code changes that would be nice to have in your commit:

I. The “routes” property is a list of key/value pairs, each pair in the form of a map, as opposed to a list of just string values. See this documentation:

https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#routes

Therefore, in ManifestParser class, line 454, “routeNameObj” should be an instance of a Map, where the Map has only one entry with key “route” and value the actual value of the route:

https://github.com/D054981/cft/blob/a0cd477f3edc37405a9d97c754e932176578d306/org.eclipse.cft.server.core/src/org/eclipse/cft/server/core/internal/application/ManifestParser.java#L454

II. If possible, please make sure your branch is in sync with the current CFT master branch and any merge conflicts are resolved in your Pull Request or your patch. At the moment, the Pull Request shows that there are merge conflicts:

https://github.com/eclipse/cft/pull/67/conflicts

If you can either update the Pull Request with these changes, or attach a patch with these changes to the bugzilla following the instructions above, that would be great.

Thanks again for the work.

**Comment by D054981** [comment]
Hi,
I did the changes mentioned and also added the "signed-off-by" to the latest commit.
The ECA is signed already. However, the ip-validation check still failes. I don't know why.

BR André

**Comment by nierajsingh** [comment]
Thanks for making the changes. Due to time constraint because we are now in RC3 for Oxygen.1, and also that you have confirmed ECA signing in your comment, I'll merge this PR in spite of the ip-validation check failures. If the Eclipse IP team still needs this submitted for IP review, I think we can attach a patch to the bugzilla and mark it for IP check later on.

Thanks again for working on this. This will be available in CFT 1.1.1 (Oxygen.1) release.

**Pull request merged**
